name: Continuous Integration Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

            - name: Install .NET Core
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: '5.0.100-preview.8.20417.9'

            - name: Restore
              run: dotnet restore LlvmMingwProjectSystem.sln
              working-directory: src

            - name: Build
              run: dotnet pack
              working-directory: src/Sunburst.LlvmMingw.Sdk

            - name: Upload NuGet package
              uses: actions/upload-artifact@v2
              if: ${{ github.action_name == 'pull_request' }}
              with:
                  name: NuGet package
                  path: bin/Packages/*.nupkg
